name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza todo dia à meia-noite
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update GitHub Stats
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api/top-langs/?username=Dominguesgabriel&hide_progress=false&count_private=true&token=${{ secrets.GH_STATS_TOKEN }}"
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update GitHub Stats"
          git push
